apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sql-insight-engine.fullname" . }}-secrets
  labels:
    {{- include "sql-insight-engine.labels" . | nindent 4 }}
type: Opaque
stringData:
  gemini-api-key: {{ .Values.secrets.geminiApiKey | quote }}
