[project]
name = "mcp-chroma"
version = "0.1.0"
description = "MCP Server for ChromaDB"
dependencies = [
    "mcp[server]",
    "chromadb==0.5.23",
    "python-dotenv",
    "uvicorn",
    "fastapi",
    "httpx",
    "google-genai",
    "prometheus-client"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
